### ISSUE TITLE
Create a type fireball.Handlers

### ISSUE THREAD

**Issue by raff** [zpatrick/fireball#1]
If you create:

type Handlers map[string]Handler

Then you can write:

  indexRoute := &fireball.Route{
    Path: "/",
    Handlers: fireball.Handlers{
      "GET": index,
    },
  }

**Comment by zpatrick** [comment]
Thanks! Added in https://github.com/zpatrick/fireball/commit/6073a278ddee57b5055bfc56e84446b79f240d63
